project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"
  preview:
    port: 3333

execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/readings.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Um apanhado dos recursos digitais de pesquisa em Relações Internacionais"

website:
  title: "RI Digitais"
#   site-url: "https://compasp23.classes.andrewheiss.com"

  favicon: "/files/favicon-512.png"

  open-graph:
    image: "/files/social-image-sp23.png"
    locale: pt_BR

  navbar:
    pinned: true
    background: "#341648"
    right:
      - text: "Introdução"
        file: md/intro/index.qmd
      - text: "A"
        file: md/A/index.qmd
      - text: "B"
        file: md/B/index.qmd
      - text: "C"
        file: md/C/index.qmd

  sidebar:
    - title: "Classes"
      style: "docked"
      search: false
      background: light
      # contents:
      #   - section: "Overview"
      #     contents:
      #       - C/index.qmd
      #   - section: "Classes"
      #     contents:
      #       - section: "1–4: Foundations of public management and governance"
      #         contents:
      #           - text: "1: Introduction to public administration and management"
      #             file: C/01-class.qmd
      #           - text: "2: Rediscovery of bureaucracy and good governance"
      #             file: C/02-class.qmd
      #           - text: "3: Quality of government and governance outcomes"
      #             file: C/03-class.qmd
      #           - text: "4: Institutions"
      #             file: C/04-class.qmd
      #       - section: "5–9: Comparative bureaucracy and civil society"
      #         contents:
      #           - text: "5: Bureaucracy and governance outcomes"
      #             file: C/05-class.qmd
      #           - text: "6: Bureaucracy and bureaucratic behavior"
      #             file: C/06-class.qmd
      #           - text: "7: Civil society and good governnace"
      #             file: C/07-class.qmd
      #           - text: "8: Civil society across countries"
      #             file: C/08-class.qmd
      #           - text: "~~9: Representative bureaucracy and philanthropy~~"
      #             file: C/09-class.qmd
      #       - section: "10–14: Regional deep dives"
      #         contents:
      #           - text: "10: The OECD"
      #             file: C/10-class.qmd
      #           - text: "11: Latin America"
      #             file: C/11-class.qmd
      #           - text: "12: Africa"
      #             file: C/12-class.qmd
      #           - text: "13: Middle East and North Africa"
      #             file: C/13-class.qmd
      #           - text: "14: Asia"
      #             file: C/14-class.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
        #   contents:
        #     - D/index.qmd
        # - section: "Preparation"
        #   contents:
        #     - D/reading-report.qmd
        #     - D/presentation-discussion.qmd
        # - section: "Essays"
        #   contents:
        #     - D/data-exploration.qmd
        #     - D/theory-in-real-life.qmd
        # - section: "Final project"
        #   contents:
        #     - D/policy-brief.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) & [Andrew Heiss](https://www.andrewheiss.com)<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
