---
title: "Coleta e Preparação do material de pesquisa"
citeproc: true
reference-location: margin
---

Toda pesquisa em ciências humanas inevitavelmente envolve três etapas, de pesquisa: preparação, execução e divulgação.

<center>
```{mermaid}
graph TD
    A(Coleta de dados e referências bibliográficas) --> B(Análise das referências e estruturação dos dados)
    B --> C(Preparação de um texto ou relatório para publicação)
    C --> A
```
</center>

Na primeira fase, o pesquisador deve buscar por fontes primárias e secundárias, bem como por dados que possam ser utilizados para a análise do objeto de estudo. Em linhas gerais, as fontes primárias são os documentos, dados e materiais que constituem o objeto de estudo em si, enquanto as fontes secundárias são as referências bibliográficas que tratam do objeto de estudo.

### Repositórios de referências
<!-- [Scopus](https://www.scopus.com/), o [Web of Science](https://www.webofknowledge.com/) -->
Para encontrar referências bibliográficas propriamente, confira o [Internet Archive Scholar](https://scholar.archive.org), [Research Rabbit](https://www.researchrabbit.ai), o [Google Scholar](https://scholar.google.com.br/), [Semantic Scholar](https://www.semanticscholar.org), [CrossRef](https://www.crossref.org),
 ou o [JSTOR](https://www.jstor.org/). Pesquisadores de diversas áreas também compartilham com frequência sua produção acadêmica em redes sociais, como [Academia.edu](https://www.academia.edu/), [ResearchGate](https://www.researchgate.net/), ou com o [Mendeley](https://www.mendeley.com/). Em alguns casos, é possível encontrar bibliografias anotadas e comentadas por acadêmicos na forma de publicações (*e.g.* [*Oxford Bibliographies in International Relations*](https://www.oxfordbibliographies.com/page/140)) ou nos sites pessoais de pesquisadoras.


#### Repositórios de documentos

O [Internet Archive](https://archive.org/) hospeda conteúdo em domínio público e torna possível retirar livros digitalmente em bibliotecas estrangeiras. Além disso, ele hospeda a Wayback Machine, responsável por fazer snapshots periódicos de uma grande parte do conteúdo da internet. Este recurso é importante para permitir referências estáveis em trabalhos acadêmicos. Nesta categoria temos ainda o [Arquivo Nacional](http://www.arquivonacional.gov.br), a [Europeana](https://www.europeana.eu/pt), a e [Biblioteca Digital Mundial](https://www.wdl.org/pt/) com coleções de museus, bibliotecas e arquivos de todo o mundo.

::: {.callout-tip}
Não deixe de explorar o Internet Archive e os repositórios públicos de material digitalizado. Trata-se de uma fonte inestimável para qualquer pesquisa em humanidades que lida com documentos históricos.
:::


#### Repositórios de código

Para encontrar códigos de programas, consulte o [Github](https://github.com), o [Gitlab](https://gitlab.com/), ou o [Bitbucket](https://bitbucket.org/). O Github é o maior repositório de código aberto do mundo, e é uma excelente fonte para encontrar códigos de programas. O Gitlab e o Bitbucket são uma alternativas ao Github, que também permitem hospedar códigos de programas. Aprender a navegar e utilizar o Github é uma habilidade importante para qualquer pesquisador, e pode ser aprendida por meio de tutoriais como [este](https://guides.github.com/activities/hello-world/).


#### Repositórios de dados

Para acessar bancos de dados em domínio público, consulte o [Our World in Data](https://ourworldindata.org/), o [Gapminder](https://www.gapminder.org/), o [World Bank Open Data](https://data.worldbank.org/), o [UNdata](https://data.un.org/), o [World Bank DataBank](https://databank.worldbank.org/home.aspx), ou o [Portal Brasileiro de Dados Abertos](http://dados.gov.br/). Talvez o melhor repositório de dados seja o [Google Dataset Search](https://datasetsearch.research.google.com/), que permite buscar por conjuntos de dados em diversos repositórios. Apesar de não ser um repositório de dados propriamente, o [Github](https://github.com) frequentemente hospeda conjuntos de dados, e é uma boa fonte para encontrar scripts de raspagem de dados.

#### Coleta de dados

A coleta de dados é uma tarefa que pode ser realizada de diversas formas. Dados podem ser coletados por meio de entrevistas, observação participante, ou por meio de questionários. Em outros casos, os dados podem ser coletados por meio de raspagem de dados de sites, ou por meio de APIs. Para este tipo de tarefa, o pesquisador pode utilizar ferramentas como o [Import.io](https://www.import.io/), o [Octoparse](https://www.octoparse.com/), ou o [ParseHub](https://www.parsehub.com/), ou scripts em [Python](https://www.python.org/), [R](https://www.r-project.org/), que podem ser escritos com o [Jupyter Notebooks](https://jupyter.org/), com [R Markdown](https://rmarkdown.rstudio.com/), ou outra linguagem de programação.^[Para aprender mais, consulte, em particular, [Python Humanities](https://pythonhumanities.com) e [Programming Historian](https://programminghistorian.org).] Em outros casos, os dados podem ser coletados por meio de experimentos, ou por meio de simulações computacionais.




**Consulte ainda:**

- [Biblioteca Digital Brasileira de Teses e Dissertações](https://bdtd.ibict.br/vufind/): [PUC MG](https://web.sistemas.pucminas.br/BDP/PUC%20Minas), [PUC SP](https://tede2.pucsp.br), [PUC Rio](http://www.ser.puc-rio.br/index.php/pos-graduacao/teses-e-dissertacoes), [PUC RS](https://repositorio.pucrs.br/dspace/handle/10923/10719/browse?type=subject&order=ASC&rpp=20&value=RELAÇÕES+INTERNACIONAIS), [UFMG](https://repositorio.ufmg.br/handle/1843/BUOS-8V4H6X), [USP](https://www.teses.usp.br/), [Unicamp](https://www.bibliotecadigital.unicamp.br/), [Unesp](https://repositorio.unesp.br/handle/11449/102), [UFRJ](https://bdtd.ibict.br/vufind/), [UFRGS](https://www.lume.ufrgs.br/handle/10183/1), [UFSC](https://repositorio.ufsc.br/handle/123456789/2), [UFPE](https://repositorio.ufpe.br/handle/123456789/2), [UFBA](https://repositorio.ufba.br/ri/handle/ri/2), [UFRN](https://repositorio.ufrn.br/handle/123456789/2), [UERJ](https://www.maxwell.vrac.puc-rio.br/colecao.php?strSecao=resultado&nrSeq=2&nrArq=2), [UFC](https://repositorio.ufc.br/handle/riufc/2), [UFSM](https://repositorio.ufsm.br/handle/1/2), [UFPR](https://acervodigital.ufpr.br/handle/1884/2), [UFPB](https://repositorio.ufpb.br/jspui/handle/123456789/2), [UFG](https://repositorio.bc.ufg.br/tede/handle/tede/2), [UFS](https://ri.ufs.br/handle/riufs/2), [UFPA](https://repositorio.ufpa.br/jspui/handle/2011/2), [UFSCar](https://repositorio.ufscar.br/handle/ufscar/2), [UFCG](https://repositorio.ufcg.edu.br/jspui/handle/riufcg/2), [UFLA](https://repositorio.ufla.br/handle/1/2), [UFV](https://repositorio.ufv.br/handle/123456789/2), [UFPI](https://repositorio.ufpi.br/jspui/handle/123456789/2), [UFMS](https://repositorio.ufms.br/handle/123456789/2), [UFAL](https://www.repositorio.ufal.br/handle/riufal/2), [UFGD](https://repositorio.ufgd.edu.br/jspui/handle/prefix/2)
- [Open Access](https://www.openaccessbutton.org/), [Open Access Journals](https://doaj.org/), [Open Access Theses and Dissertations](https://oatd.org/), [Open Access Books](https://www.doabooks.org/), [Open Access Repositories](https://www.opendoar.org/)
- [Internet Archive](https://archive.org/), [Internet Archive Wayback Machine](https://archive.org/web/), [Internet Archive Scholar](https://scholar.archive.org/)
- [Portal Brasileiro de Dados Abertos](http://dados.gov.br/)





---
references:
- id: ThuHist
  abstract: |-
    Tucídides
    2 vols
  author:
    - family: Thucydides
      given: ''
  call-number: '0003.001'
  citation-key: ThuHist
  container-title: Thucydidis Historiae
  editor:
    - family: Jones
      given: H. S.
  event-place: Oxford
  issued:
    - year: 1942
  publisher: Clarendon
  publisher-place: Oxford
  title: Historiae
  title-short: Thu
  type: chapter
...



